print("Welcome to the tip calculator")
bill=input("what is the total bill?")
new_bill=float(bill)
tip=input("what percentage tip would you like to give? 10,12,or 15?")
new_tip=float(tip)
people_split=input("how many people to split the bill?")
new_people_split=int(people_split)
new_bill_tip=round(((new_bill*new_tip/100)+new_bill)/new_people_split, 2)
print(new_bill_tip)
