print("Hello World")
print("Day1-Python Print function")
print("The Function is declared like this:")
print("print('what to print)")
print("Hello World\nHello World")
print("Georgina"+"Chepkorir")
print("Hello"+" "+"Georgina")
print("String Concatenation is done with the" +" "+"sign.")
print('eg print("Hello"+"World")')
print(len(input("what is your name?")))
print(len(jack))
name=input("what is your name?")
length=len(name)